[package]
name = "consumer_faer_v0_24"
version = "0.0.0"
edition = "2024"
publish = false
rust-version = "1.87"

[lib]
path = "../../src/faer.rs"

[features]
parallel = ["lazymatrix/parallel"]

[dependencies]
lazymatrix = { path = "../../../..", default-features = false, features = ["faer_v0_24"] }
faer = { version = "0.24", default-features = false, features = ["std", "linalg"] }
