[package]
name = "consumer_nalgebra_v0_35"
version = "0.0.0"
edition = "2024"
publish = false
rust-version = "1.89"

[lib]
path = "../../src/nalgebra.rs"

[features]
parallel = ["lazymatrix/parallel"]

[dependencies]
lazymatrix = { path = "../../../..", default-features = false, features = ["nalgebra_v0_35"] }
nalgebra = { version = "0.35" }
nalgebra-sparse = "0.12"
